In [1]:
#NLP - Problem Statement - Fake News Detection or Detection
#Algorithm - TfidfVectorizer

In [2]:
#1.IMPORTING LIBRARIES

import pandas as pd
# import → Python keyword that brings the specified module into the current program
# pandas → Python library used for data manipulation and analysis, especially with tables (DataFrames)
# as → Python keyword used to give an imported item a shorter alias/nickname
# pd → The alias assigned to pandas, used to call the library more easily in code

import numpy as np
# import → Python keyword that brings the specified module into the current program
# numpy → Python library used for numerical computing and working with arrays
# as → Python keyword used to give an imported item a shorter alias/nickname
# np → The alias assigned to numpy, used to call the library more easily in code

import itertools
# import → Python keyword that brings the specified module into the current program
# itertools → Built-in Python module that provides tools for creating and working with iterators (e.g. combinations, loops)

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
# from → Python keyword used to import specific parts (not the whole module) from a library
# sklearn.feature_extraction.text → Module in scikit-learn for converting text into numerical features
# import → Brings the specified classes into the current program
# CountVectorizer → Class that converts text into a matrix of word counts
# TfidfVectorizer → Class that converts text into a matrix of TF-IDF weighted scores
# HashingVectorizer → Class that converts text into a fixed-size numerical matrix using hashing

from sklearn.model_selection import train_test_split
# from → Python keyword used to import specific parts from a library
# sklearn.model_selection → Module in scikit-learn for splitting and validating datasets
# import → Brings the specified function into the current program
# train_test_split → Function that splits data into training and testing sets

from sklearn.linear_model import PassiveAggressiveClassifier
# from → Python keyword used to import specific parts from a library
# sklearn.linear_model → Module in scikit-learn containing linear model algorithms
# import → Brings the specified class into the current program
# PassiveAggressiveClassifier → Classification algorithm that updates aggressively on misclassified examples

from sklearn.naive_bayes import MultinomialNB
# from → Python keyword used to import specific parts from a library
# sklearn.naive_bayes → Module in scikit-learn containing Naive Bayes algorithms
# import → Brings the specified class into the current program
# MultinomialNB → Naive Bayes classifier suited for text/word-count data

from sklearn import metrics
# from → Python keyword used to import specific parts from a library
# sklearn → scikit-learn library, used for machine learning
# import → Brings the specified module into the current program
# metrics → Module containing tools to evaluate model performance (accuracy, confusion matrix, etc.)

import matplotlib.pyplot as plt
# import → Python keyword that brings the specified module into the current program
# matplotlib.pyplot → Module used for creating plots and visualizations
# as → Python keyword used to give an imported item a shorter alias/nickname
# plt → The alias assigned to matplotlib.pyplot, used to call plotting functions more easily

# This cell imports all the libraries needed for text vectorization, model training (PassiveAggressiveClassifier, MultinomialNB), 
# evaluation (metrics), and visualization (plt).

In [3]:
#2.LOADING THE DATASET

df = pd.read_csv('news.csv', index_col=None)
# df → Variable storing the loaded dataset
# pd.read_csv → Function that reads a CSV file and loads it into a DataFrame
# 'news.csv' → Name of the file being read
# index_col=None → Tells pandas not to use any column as the row index (uses default numeric index)

# This cell loads the news.csv file into a DataFrame called df.

In [4]:
#3.VIEWING THE DATASET

df
# df → Displays the contents of the df DataFrame (the loaded news.csv data)

# This cell outputs df to inspect the loaded dataset.

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [5]:
#4.DROPPING UNWANTED COLUMN

dataset = df.drop("Unnamed: 0",axis=1)
# dataset → Variable storing the cleaned DataFrame
# df.drop → Method that removes a specified column or row from the DataFrame
# "Unnamed: 0" → Name of the column being removed (usually a leftover index column from the CSV)
# axis=1 → Specifies that a column (not a row) should be dropped

# This cell removes the unwanted "Unnamed: 0" column from df and stores the result in dataset.

In [6]:
#5.VIEWING THE CLEANED DATASET

dataset
# dataset → Displays the contents of the dataset DataFrame (news data without the "Unnamed: 0" column)

# This cell outputs dataset to inspect the cleaned data.

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [7]:
#6.EXTRACTING THE TARGET LABEL

y = dataset["label"]
# y → Variable storing the target/output column
# dataset["label"] → Selects the "label" column from dataset (e.g. REAL/FAKE)

# This cell extracts the "label" column from dataset and stores it in y as the target variable.

In [8]:
#7.SPLITTING DATA INTO TRAIN AND TEST SETS

X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)
# X_train, X_test, y_train, y_test → Four variables that will receive the split data
# = → Assignment operator; unpacks the results into these variables
# train_test_split → Function that splits data into training and testing sets
# dataset['text'] → Selects the "text" column from dataset (the input feature)
# y → The target/output column (labels) defined earlier
# test_size=0.33 → Reserves 33% of the data for testing, 67% for training
# random_state=53 → Fixed seed value so the split is the same every time the code runs

# This cell splits the text data and labels into training (67%) and testing (33%) sets.

In [9]:
#8.VECTORIZING TEXT USING TFIDFVECTORIZER

tfidf_vectorizer = TfidfVectorizer(stop_words='english')
# tfidf_vectorizer → Variable storing the vectorizer object
# TfidfVectorizer → Class that converts text into a matrix of TF-IDF weighted scores
# stop_words='english' → Removes common English words (e.g. "the", "is", "and") that add little meaning

tfidf_train = tfidf_vectorizer.fit_transform(X_train)
# tfidf_train → Variable storing the vectorized training data
# tfidf_vectorizer.fit_transform → Learns the vocabulary from X_train and converts it into a TF-IDF weighted matrix
# (X_train) → The training text data being vectorized

print(tfidf_train)
# print → Built-in function that displays output
# tfidf_train → Displays the resulting sparse matrix of TF-IDF scores

tfidf_test = tfidf_vectorizer.transform(X_test)
# tfidf_test → Variable storing the vectorized testing data
# tfidf_vectorizer.transform → Converts X_test into a TF-IDF weighted matrix using the same vocabulary learned from X_train
# (X_test) → The testing text data being vectorized

# This cell converts the training and testing text into numerical TF-IDF weighted matrices using TfidfVectorizer.

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119820 stored elements and shape (4244, 56922)>
  Coords	Values
  (1, 42470)	0.07711040274149526
  (1, 12105)	0.15008066461476866
  (1, 54177)	0.13782629144711137
  (1, 50628)	0.061296988343109586
  (1, 15924)	0.3479045460649079
  (1, 44520)	0.4973826512693341
  (1, 51896)	0.11596517664605868
  (1, 35783)	0.30902690818827977
  (1, 35256)	0.12628385718450857
  (1, 21881)	0.21271688045815978
  (1, 42534)	0.06081715886809217
  (1, 8399)	0.08729542880625335
  (1, 29531)	0.1454406205718245
  (1, 15927)	0.4973826512693341
  (1, 25686)	0.13550453594288983
  (1, 49203)	0.1672740861784377
  (1, 16814)	0.10404977746548139
  (1, 36087)	0.12648679854389897
  (1, 21568)	0.1007920919566398
  (1, 25684)	0.1030420922189754
  (1, 38823)	0.06048803110658644
  (1, 47506)	0.14539060877460044
  (1, 36831)	0.10772488937433067
  (2, 16972)	0.1606296088662543
  (2, 762)	0.48803966069171073
  :	:
  (4243, 41435)	0.02969665315895183
  (4243, 53607)	

In [10]:
#9.INSPECTING TFIDF_TRAIN OBJECT

dir(tfidf_train)
# dir → Built-in function that lists all attributes and methods available on an object
# tfidf_train → The vectorized training data (sparse TF-IDF matrix) whose attributes/methods are being listed

# This cell lists all the methods and properties available on the tfidf_train sparse matrix object.

['T',
 '__abs__',
 '__abstractmethods__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pow__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_abc_impl',
 '_add_dense',
 '_add_sparse',
 '_allow_nd',
 '_argminmax',
 '_argminmax_axis',
 '_ascontainer',
 '_asfptype',
 '_binopt',
 '_broadcast_to',
 '_bsr_container',
 '_comparison',
 '_container',
 '_c

In [11]:
#10.COUNTING VOCABULARY SIZE

len(tfidf_vectorizer.get_feature_names_out())
# len → Built-in function that returns the number of items
# tfidf_vectorizer.get_feature_names_out → Method that returns the list of all unique words (vocabulary) learned by the vectorizer
# () → Calls the method with no extra arguments

# This cell outputs the total number of unique words in the vocabulary learned by tfidf_vectorizer.

56922

In [12]:
#11.VIEWING TFIDF_TRAIN AS A FULL ARRAY

print(tfidf_train.toarray())
# print → Built-in function that displays output
# tfidf_train.toarray → Method that converts the sparse TF-IDF matrix into a full (dense) NumPy array
# () → Calls the method with no extra arguments

# This cell prints the full TF-IDF matrix as a regular array instead of a sparse matrix.

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
#12.TRAINING AND EVALUATING MULTINOMIAL NAIVE BAYES MODEL (TF-IDF)

clf = MultinomialNB()
# clf → Variable storing the classifier object
# MultinomialNB() → Creates a new instance of the Multinomial Naive Bayes classifier

clf.fit(tfidf_train, y_train)
# clf.fit → Method that trains the model
# tfidf_train → The vectorized training text data (TF-IDF weighted input)
# y_train → The training labels (output)

pred = clf.predict(tfidf_test)
# pred → Variable storing the model's predictions
# clf.predict → Method that predicts labels for new/unseen data
# tfidf_test → The vectorized testing text data (TF-IDF weighted)

score = metrics.accuracy_score(y_test, pred)
# score → Variable storing the accuracy result
# metrics.accuracy_score → Function that compares actual vs predicted labels to calculate accuracy
# y_test, pred → Actual labels vs predicted labels being compared

print("accuracy:   %0.3f" % score)
# print → Built-in function that displays output
# "accuracy:   %0.3f" → Text label with a placeholder for a number formatted to 3 decimal places
# % score → Inserts the score value into the placeholder

cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
# cm → Variable storing the confusion matrix
# metrics.confusion_matrix → Function that shows counts of correct/incorrect predictions per class
# y_test, pred → Actual labels vs predicted labels being compared
# labels=['FAKE', 'REAL'] → Specifies the order of classes in the matrix

# This cell trains a Naive Bayes classifier on TF-IDF features, predicts on test data, prints accuracy, and builds a confusion matrix comparing 
# FAKE vs REAL predictions.

accuracy:   0.857


In [14]:
#13.GENERATING CLASSIFICATION REPORT

from sklearn.metrics import classification_report
# from → Python keyword used to import specific parts from a library
# sklearn.metrics → Module in scikit-learn containing evaluation metric functions
# import → Brings the specified function into the current program
# classification_report → Function that summarizes precision, recall, F1-score, and support for each class

report = classification_report(y_test, pred)
# report → Variable storing the classification report
# classification_report → Compares actual vs predicted labels and generates the summary
# y_test, pred → Actual labels vs predicted labels being compared

# This cell generates a detailed classification report showing precision, recall, and F1-score for each class.

In [15]:
#14.VIEWING THE CLASSIFICATION REPORT

print(report)
# print → Built-in function that displays output
# report → Displays the classification report (precision, recall, F1-score, support for each class)

# This cell prints the classification report to review the model's performance in detail.

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.80      0.97      0.88      1083

    accuracy                           0.86      2091
   macro avg       0.88      0.85      0.85      2091
weighted avg       0.88      0.86      0.85      2091



In [16]:
#15.VIEWING FIRST TEXT ENTRY

dataset["text"][0]
# dataset["text"] → Selects the "text" column from dataset
# [0] → Selects the first entry (row index 0) from that column

# This cell displays the very first news text entry in the dataset.

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [17]:
#16.VIEWING FIRST VECTORIZED ROW

tfidf_train[0]
# tfidf_train → The vectorized training data (sparse TF-IDF matrix)
# [0] → Selects the first row (row index 0) from the matrix

# This cell displays the TF-IDF vectorized representation of the first row in tfidf_train.

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 56922)>

In [18]:
#17.RE-VECTORIZING TRAINING TEXT USING TFIDFVECTORIZER

tfidf_vectorizer = TfidfVectorizer(stop_words='english')
# tfidf_vectorizer → Variable storing the vectorizer object
# TfidfVectorizer → Class that converts text into a matrix of TF-IDF weighted scores
# stop_words='english' → Removes common English words (e.g. "the", "is", "and") that add little meaning

tfidf_train = tfidf_vectorizer.fit_transform(X_train)
# tfidf_train → Variable storing the vectorized training data
# tfidf_vectorizer.fit_transform → Learns the vocabulary from X_train and converts it into a TF-IDF weighted matrix
# (X_train) → The training text data being vectorized

# This cell re-vectorizes X_train into tfidf_train using TfidfVectorizer.

In [19]:
#18.VIEWING FIRST TRAINING TEXT ENTRY

X_train[0]
# X_train → The training text data (input features)
# [0] → Selects the first entry (index 0) from X_train

# This cell displays the first text entry in X_train.

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [20]:
#19.PREDICTING LABEL FOR FIRST TRAINING ENTRY

clf.predict(tfidf_train[[0]])
# clf.predict → Method that predicts the label for given input data
# tfidf_train[[0]] → Selects the first row from tfidf_train (kept in matrix form using double brackets)

# This cell predicts the label for the first vectorized training entry using the trained classifier.

array(['FAKE'], dtype='<U4')